// Code generated by "stringer -type cError -linecomment -output errors_string.go"; DO NOT EDIT.

package ger

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrRestart-1]
	_ = x[ErrAllCancelled-2]
	_ = x[ErrStopped-3]
	_ = x[ErrSupervisorIsNotRunning-4]
}

const _cError_name = "restart meall tasks are cancelledtask is stoppedsupervisor is not running"

var _cError_index = [...]uint8{0, 10, 33, 48, 73}

func (i cError) String() string {
	i -= 1
	if i >= cError(len(_cError_index)-1) {
		return "cError(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _cError_name[_cError_index[i]:_cError_index[i+1]]
}
